文件增加颜色标记功能
zhuxb711/RX-Explorer pull request #158
Opened 2021-04-20 09:28 UTC by silentmoooon

![zzzz](https://user-images.githubusercontent.com/9210514/115372735-c8a53480-a1fd-11eb-9016-90cfc90846f8.gif)

2021-04-20 10:41 UTC, zhuxb711 requested changes

2021-04-20 10:41 UTC, zhuxb711 commented on RX_Explorer/View/FilePresenter.xaml.cs
> +        }
我觉得对于Page这个级别的对象最好不要给他加上INotifyPropertyChanged接口，Page的主要作用是承载这些页面上的对象和处理控件事件，最好不要作为一个类似于数据模型的东西来用，它的地位是ViewController，虽然我这里没有用MVVM

2021-04-20 10:41 UTC, zhuxb711 commented on RX_Explorer/View/FilePresenter.xaml
>                            ToolTipService.ToolTip="剪切"
遵循这里的XAML格式，应当每个属性单独一行

2021-04-20 10:41 UTC, zhuxb711 commented on RX_Explorer/View/FilePresenter.xaml.cs
> +        }
对于磁盘缓慢的用户，这里在静态构造函数中去同步取数据库的内容，可能导致界面无响应

2021-04-20 10:41 UTC, zhuxb711 commented on RX_Explorer/View/FilePresenter.xaml.cs
> +        }
你这里结合你更改FileSystemStorageItemBase里面，其实你是要取到某个FileSystemStorageItemBase对象应当显示什么颜色对吧。我的建议是，删除此处的内容，更改SQLite类的GetFileColorAsync函数，能够直接找到对应的Path的颜色，然后什么时候去取这个颜色呢？最好是放在FileSystemStorageItemBase中的LoadMorePropertiesAsync(如果你这个颜色和文件类型无关，则不必放入LoadMorePropertiesCore这个由子类重写的方法)，(放在LoadMorePropertiesAsync中try括号的最下面，这样不会阻止最优先的内容显示)。首先这个方法是一个异步方法，可以异步取SQLite，其次这样可以优化性能，因为不是每个FileSystemStorageItemBase对象都是要显示这个颜色的，很多FileSystemStorageItemBase对象不一定是呈现到界面上去，而是作为普通文件对象用于各个地方。而LoadMorePropertiesAsync函数仅在界面上呈现的时候会予以分阶段加载，因此节省了大量的开销。最后，引入FilePresenter对象的引用之后，加大了FileSystemStorageItemBase与FilePresenter这个无关对象的耦合程度，在这之前FileSystemStorageItemBase是可以脱离任何界面而存在的

2021-04-20 10:44 UTC, zhuxb711 commented
感觉你这个功能类似打Tag那种，很早就有人喊了要这个，思路不错~~~~~提一句，这样有这个Tag之后是不是搜索(或者详细列表的筛选功能)也要变一变了

2021-04-20 13:33 UTC, silentmoooon commented on RX_Explorer/View/FilePresenter.xaml.cs
> +        }
em.. 一开始是硬编码,后来发现太多了.  那外CommandBar貌似不能分组? 只能挨个来控制 .

2021-04-20 13:34 UTC, silentmoooon commented on RX_Explorer/View/FilePresenter.xaml.cs
> +        }
好 ,明天再看下.

2021-04-20 13:36 UTC, silentmoooon commented
那又是不少工作量了 哈哈.
交互这块你觉得还有啥问题没.

2021-04-21 02:33 UTC, zhuxb711 commented
我可以帮助你更改一下上面有关查Color那一块的内容

2021-04-21 03:26 UTC, zhuxb711 commented
发现一些BUG，提一下，不需要你改，我已经改了。
1. 你忘记更新MaintanceTask中的关于更新SQLite数据库的语句了，任何针对SQLite的结构更新都应当在这个任务中执行，因为你在SQLite那里写的语句一旦初始化完成后不会重复执行。这个任务负责在用户每次更新App的时候执行一些维护任务，其中就可以包括更新数据库结构等任务。否则用户将不会拥有你的那个FileColor表。
2. Color.ToString()不是将这个颜色转换为对应的十六进制的值，这样你存进去的就有问题，应该用ColorHelper中的ToHex()方法转换

2021-04-21 07:43 UTC, zhuxb711 approved these changes

2021-04-21 07:45 UTC, zhuxb711 commented
发现另外的问题，就是你只更改了详细列表的颜色，其他模式下没有更改，这些均已在最新的提交中修复了

2021-04-21 07:48 UTC, silentmoooon commented
啊, 你不说我都没注意还有其他模式了.  平时只用详细列表模式.
唉  今天有点忙..  暂时没空弄这个了.

2021-04-21 07:59 UTC, zhuxb711 commented
最后一个小问题就是是否要保持住当前的设计？
那个标签的进入方式现在是鼠标指针进去就会进入，是鼠标进入就变动好还是需要进一步的点击？在这一点上想听听你的想法，因为我也不确定哪种比较好

2021-04-21 08:07 UTC, silentmoooon commented
其实这个问题我也想问你来着,现在这样对桌面用户应该是可以的,但好像平板用户不好操作?   
其实我一开始也是搞成点击进入的,结果不知道为啥每次点了下面的菜单就收起来了,才改成现在这样的. 哈哈.

2021-04-21 08:18 UTC, zhuxb711 commented
我觉得触摸屏应该也阔以用吧~~~~但没有测试过。
点击Button自动关闭Flyout应该是这个控件的默认行为(有的时候不好使，所以我代码中才会有CloseAllFlyout这个函数)

你看看有木有啥问题，翻译文件我也添加了，应该木有啥大问题了

2021-04-21 09:42 UTC, silentmoooon commented
试了下触摸屏,不是太好.  要按住 然后出现颜色菜单后再移动到别的按钮上再松开.

2021-04-22 03:30 UTC, zhuxb711 commented
难以让这个操作兼容触摸屏，现在CommandBarFlyout的行为是只要Click事件触发它就会关闭自己，无法单独禁用Click事件

2021-04-22 03:46 UTC, zhuxb711 commented
机智的我略加思考找到方法啦， @silentmoooon 可以测试一下吗？

2021-04-22 04:05 UTC, silentmoooon commented
试了下好像没区别

2021-04-22 04:07 UTC, zhuxb711 commented
诶Border不应该引发Click事件呀，还是会关闭右键菜单？

2021-04-22 04:12 UTC, silentmoooon commented
碰到的一瞬间就触发鼠标进入事件 然后松开就触发同一位置蓝色tag的click事件.

2021-04-22 04:44 UTC, silentmoooon commented
![image](https://user-images.githubusercontent.com/9210514/115656840-79c7de00-a368-11eb-9ace-630f870b5b8b.png)

最新预览版倒是加了个这样的属性

2021-04-22 06:16 UTC, zhuxb711 commented
那个没用，我上面让你测试的是触摸屏现在能不能正常通过点击的方式来打标签啦？肯定还是指针在上面就切换的因为我没有改这一块的逻辑

2021-04-22 06:34 UTC, silentmoooon commented
不是,触摸屏的问题的是,摸到tag按钮那一瞬间就触发显示颜色按钮了,然后会一并按到显示出来的蓝色按钮,再松开就触发到蓝色按钮点击事件了,等于摸一下就触发了2次操作,  而不是因为触发click事件导致右键菜单关闭.
所以我在想要不干脆升级一下,加上AlwaysExpanded,这样click事件就不会导致菜单关闭,就可以把鼠标进入事件改成click事件了,这样键鼠和和触屏也就统一了

2021-04-22 06:46 UTC, zhuxb711 commented
> 不是,触摸屏的问题的是,摸到tag按钮那一瞬间就触发显示颜色按钮了,然后会一并按到显示出来的蓝色按钮,再松开就触发到蓝色按钮点击事件了,等于摸一下就触发了2次操作, 而不是因为触发click事件导致右键菜单关闭.
> 所以我在想要不干脆升级一下,加上AlwaysExpanded,这样click事件就不会导致菜单关闭,就可以把鼠标进入事件改成click事件了,这样键鼠和和触屏也就统一了

我看了AlwaysExpanded属性，它只确保弹出的时候SecondaryCommand处于展开状态并消除PrimaryCommand最右侧的那三个小点(看PR描述是这样，我没有实际用过)。另外呢WinUI2.6还处于预览版状态所以有些小问题，比较明显的是RX换装WinUI 2.6预览之后，最下方的辅助菜单弹出的位置不对了，就是这个东西：
![image](https://user-images.githubusercontent.com/42038175/115668248-7557f100-a379-11eb-9261-94e5039a4210.png)

2021-04-22 06:54 UTC, silentmoooon commented
试了下,AlwaysExpanded开启后  点击事件不会自动收起SecondaryCommand了.
确实,下面这个菜单位置不对了..
那要不先不管触屏? 好像没有更好的办法.

2021-04-22 07:01 UTC, zhuxb711 commented
要不就狠下心换装新版WINUI控件，然后移除底下这个菜单的灰黑色弹出部分。这个菜单其实是早期WinUI2.5版本之前的时候，右键菜单在触摸屏下没法通过点击有二级菜单的展开二级菜单而做的一个辅助触摸的组件，现在好像右键菜单对触摸屏没啥大问题了吧？我觉得精简的话可以精简得只剩主要几个命令就可以了，直接全部拿掉也不是不行，但我现在觉得这个东西放底下还有点好看

2021-04-22 07:09 UTC, silentmoooon commented
"现在好像右键菜单对触摸屏没啥大问题了吧？"  试了没啥问题.
 我倒觉得全干掉得了.  ,好像就"多选"有点用

2021-04-22 07:13 UTC, zhuxb711 commented
这个地方其实可以用作其他的用途，全干掉了以后有啥新功能需要往上加的话那要从历史记录里面再把它扒出来了

2021-04-22 07:29 UTC, silentmoooon commented
也是.
对了,这个untag换成心碎会不会好点,不然看起来有点像"白色标记"
![image](https://user-images.githubusercontent.com/9210514/115673596-66743d00-a37f-11eb-9167-3ea5af114e3c.png)

2021-04-22 07:34 UTC, zhuxb711 commented
可以，移除下面的菜单的工作就我来吧，（那我就保留底下菜单中的主要命令，然后移除其他的部分），你看看上面的切换标记的那个Button(被我换成Border那个)，是不是要改回来然后用Click事件去做切换(升级WinUI2.6 Pre)

2021-04-22 07:36 UTC, zhuxb711 commented
好像我点了一下心形之后它只剩一半了？
![image](https://user-images.githubusercontent.com/42038175/115674644-72143380-a380-11eb-8363-00fd3df07770.png)

2021-04-22 07:37 UTC, silentmoooon commented
额 我这没遇到过这样的情况

2021-04-22 07:45 UTC, zhuxb711 commented
大概就是，你点心形切换到标记页，然后再随便点一个颜色的标记，你会发现这个菜单是左边先被裁剪右侧才跟着有关闭动画的

2021-04-22 07:57 UTC, silentmoooon commented
好像真是这样, 
如果改成默认显示标记页,然后再点返回到操作页,这时候随便点个复制之类的,就会出现右边裁剪的情况.

2021-04-22 08:07 UTC, zhuxb711 commented
你有空去WinUI的issue那里提交一个issue吗？康康微软怎么说

2021-04-22 09:17 UTC, silentmoooon commented
你提吧,  我英语不行 ,- - !

2021-04-22 09:31 UTC, zhuxb711 commented
我提交了一个新的Commit，对触摸屏和鼠标做了区分，你看看，理论上现在触摸屏已经Ok了但我这里没有设备可以测试

2021-04-22 09:44 UTC, silentmoooon commented
坑,把返回改成点击事件后, 它就...也会裁剪

加上你这个新的commit后,启不来了.

2021-04-22 09:45 UTC, zhuxb711 commented
你回退到WinUI 2.5版本

2021-04-22 09:45 UTC, zhuxb711 commented
然后重新生成

2021-04-22 09:49 UTC, silentmoooon commented
![image](https://user-images.githubusercontent.com/9210514/115693970-025b7400-a393-11eb-9bbb-9e23c50caee3.png)

也不行.. 然后就卡在启动界面了

2021-04-22 09:50 UTC, zhuxb711 commented
哦这个问题啊，这是切换WinUI后的常见问题，菜单中卸载RX后重新部署就行

2021-04-22 10:02 UTC, silentmoooon commented
> 我提交了一个新的Commit，对触摸屏和鼠标做了区分，你看看，理论上现在触摸屏已经Ok了但我这里没有设备可以测试

这下OK了

2021-04-22 10:06 UTC, zhuxb711 commented
先不要切换到WinUI 2.6 Pre，Bug还不少，那这个成功解决了触摸屏的问题的话，我就准备合并了哦，你还有其他改进吗？我会再改一下翻译文件，你如果只有那个白色的心形图标需要改的话，你可以把它的代码发给我我来一并改了

2021-04-22 10:08 UTC, silentmoooon commented
EA92

2021-04-22 10:15 UTC, zhuxb711 commented
Ok，关于那个CommandBarFlyout的问题我已经提交Issue了

2021-04-22 11:27 UTC, zhuxb711 commented
发现了一个bug，专用于lnk文件的右键菜单没有添加与Tag相关的代码。不过我已经搞好啦，准备合并~~~
感谢您提交的PR和这两天的联合Debug

2021-04-22 11:30 UTC, silentmoooon commented
emmm~  都忘了还有它的存在.

2021-04-22 15:12 UTC, merged

2021-04-26 07:09 UTC, zhuxb711 commented
![image](https://user-images.githubusercontent.com/42038175/116042508-12c86300-a6a1-11eb-998f-0c487551104c.png)
为改善对比度问题，我计划将标记改为这样，不只是刷文字，因为底色是透明的那样很不好确定对比度，你觉得呢？我换了新的配色
![image](https://user-images.githubusercontent.com/42038175/116042664-41ded480-a6a1-11eb-8ee1-3500db1c30d3.png)

2021-04-26 07:37 UTC, silentmoooon commented
感觉是个不错的方式