快速启动移动到导航栏(可通过~键展开收起), thisPC移动到FileControl之下
zhuxb711/RX-Explorer pull request #212
Opened 2021-05-03 14:37 UTC by silentmoooon

把快速启动和thispc改了一下,你看这样行不

2021-05-03 17:54 UTC, zhuxb711 commented
有一些小问题，比如垂直拆分窗口在主页上按了是没用的，另外返回键也删除掉了？

2021-05-04 03:34 UTC, silentmoooon commented
改了一下,放到FilePresenter下了,之前没注意这个拆分视图.  然后就是那个展示方式在thispc也没效了, 要不在thispc下给它禁用?
返回键暂时给隐藏了,感觉改成这样后返回健的作用就小些了.  emm... 不知道其他人会不会,我反正总是把它和goback搞混..哈哈.
发现还有个奇怪的问题, 如果启动时选择了"恢复上次打开的标签页",如果上次打开的是盘符根目录下,则启动时加载不出来.
会卡在while(!BladeViewer.IsLoad) 那. 调试了好久没找到原因.

2021-05-04 10:04 UTC, zhuxb711 requested changes
有很多问题，代码重构，特别是这种大型的架构重构，是要新设计一种方案的。我在你的PR里面看到了各种兼容目前架构的妥协和特殊处理，Path == ThisPC的语句到处散落得都是。你这样的"兼容性更改"会导致以后难以维护代码，因为每一处之前写的和之后写的你都必须考虑是不是要兼容你加进去的那些特殊处理。架构变动不是架构兼容，RX原本设计本身就是ThisPC作为最外面一层，你进行大量的架构变更，这本来就不是容易的事情，更加不是在各种通用数据模型中添加特殊处理使得这些模型的抽象倒退成为某种存在特殊处理的模型，代码的更改不是只要能跑就行，还要追求优雅，优雅的目的不只是好看，还具备优良的可维护性。如果各处都需要这种兼容代码，那说明当前的架构不适合需要进行重大重构，那你可能需要一些新的数据模型，新的结构来完成这一切。目前看来我很难批准这些代码的合并，它们带来了极高的维护难度，试图在旧框架下兼容完成新功能是不太合适的，最终它们会变成难以承受的负担。

2021-05-04 10:10 UTC, zhuxb711 commented on RX_Explorer/View/FilePresenter.xaml.cs
> +                }
这里为什么注释了？

2021-05-04 10:10 UTC, zhuxb711 commented on RX_Explorer/Class/QuickStartItem.cs
> +        }
为什么要恢复 ＋ 号图标，这是一个很久之前就取消了的功能，现在有右键菜单可以添加。另外就算这么使用，你的+号是偏上的，因为它是直接套用原来的模板的，你这需要模板选择器

2021-05-04 10:17 UTC, zhuxb711 commented
你的设计思想是试图让ThisPC整个变成文件夹对象。我不知道这是不是一个好办法，因为你现在其实是尝试让一个本来就不是文件夹的对象通过各处的判断代码去伪装成一个文件夹对象，不用想，这肯定会导致很多的BUG，所以你不得不在里面各处进行修修补补，说实话有点乱糟糟的。

新的这种架构设计已经与旧的设计完全不兼容了，因此整个架构都要天翻地覆，这也是为什么我迟迟不动这一块的原因，因为我不确定哪种方法更加好，但肯定不能够是通过给各处打小补丁来完成的方式，维持架构的简洁性，不仅仅是效果达到，是一件不容小觑的工作。

你的这种方法会导致以后的大量工作都必须存在兼容机制，增加了很多维护难度，虽然你现在写得快能够达到目的，但牺牲了大量的可维护性

2021-05-04 11:14 UTC, zhuxb711 commented
让我想想改怎么去做，这个PR先放一放吧，我有思路了再给你这个PR提交一些Commit。你有好的思路也可以分享。

2021-05-05 02:16 UTC, silentmoooon commented on RX_Explorer/View/FileControl.xaml.cs
>                      }
一开始理解错逻辑了... 但改了好像也没影响?

2021-05-05 02:16 UTC, silentmoooon commented on RX_Explorer/View/ThisPC.xaml
>              <ColumnDefinition Width="5*" />
我这个设想中这个类已经没用了. 之前改一下只是看下效果.

2021-05-05 02:16 UTC, silentmoooon commented on RX_Explorer/View/FilePresenter.xaml.cs
> +                }
额..应该是误注释忘记解除了.

2021-05-05 02:17 UTC, silentmoooon commented on RX_Explorer/Class/QuickStartItem.cs
> +        }
改成现在这种显示方式后. 应用刚好是满排的话, 下面不会显示空白部分了.. 不好在空白部分右键了..所以给它加个占位图标.

2021-05-05 02:18 UTC, silentmoooon commented
唉.  此台电脑不是个文件夹.. 很麻烦啊. 除了搞这种兼容的路子,我也想不到更好的法了. 
但又觉得这功能挺迫切的

2021-05-05 09:06 UTC, zhuxb711 commented
你对地址栏的更改有进行过测试吗？改动似乎把灰色地址块整个整废了，你改了也不测试一下的？

2021-05-05 09:20 UTC, zhuxb711 commented
Nevermind，我已经在进行一些改动了，你就不要改了。提交代码前要测试好，要考虑全面，比如你把左上角的返回按钮删除掉了，那你打算怎么从内置查看器中出来？

2021-05-06 01:28 UTC, zhuxb711 commented
我撤销了你的Commit，然后手动将新的架构和你的一些思路合并了，这有助于在大的变化之后避免繁琐的合并你我的更改。返回键还是不能去掉，因为这样用户会卡死在内置查看器里

2021-05-06 11:40 UTC, zhuxb711 commented
你有没有注意到，不用VS调试，直接运行的时候，你点一下快速启动，就会崩溃。如果附加调试器，一点问题都没有

2021-05-06 15:46 UTC, zhuxb711 commented
捡了一些漏，恢复了一些错过的设计，我看到你给QuickStartType增加了一个字段，但是有些地方考虑不太周全，因为QuickStartItem是允许拖拽的，会报错，不应将AddButton考虑进来。最后上面提到的不加调试器才会出现的BUG，我用WinDbg找到了原因了，Style写错了，不知道为什么VS没有报错

2021-05-06 15:52 UTC, zhuxb711 commented
数据模板选择器我也写上了，AddButton是不允许拖拽的，这方面我也做了拦截。你看看还有什么要补充或者改进的？
最后您购买了RX了嘛？如果没有，可以给我一个邮箱我送你一个小兑换码嘿嘿~~😊

2021-05-06 15:54 UTC, zhuxb711 approved these changes

2021-05-06 16:08 UTC, zhuxb711 commented
小提示：以后如果需要对FileSystemStorageFolder这种基础通用模型作出特殊处理的时候，不妨创建一个它的子类，利用多态来重写FileSystemStorageFolder的行为，这样就可以不用破坏FileSystemStorageFolder的默认处理方式，但又更改了FileSystemStorageFolder的行为，从而满足特殊的需求(比如我这次引入的RootStorageFolder类)

2021-05-07 01:20 UTC, silentmoooon commented
前进后退那里还是有点问题.
然后地址栏的灰色,如果回退到thispc的话就都没了. 

还有2个不是这PR的问题也顺便提一下.
1个是上次说的,启动时恢复上次打开的标签页,如果是盘符根目录就打不开.
还有一个是,随便在一个文件夹下点开列头的筛选菜单, 然后再切换到其他应用,rx就挂了.

兑换码的话  感觉也没必要吧.  反正代码在手.

2021-05-07 02:20 UTC, zhuxb711 commented
前进后退有什么问题嘛？地址栏确实回到ThisPC之后就会删除记录，这个有点难搞，理论上ThisPC不属于任何路径的一部分

2021-05-07 04:42 UTC, zhuxb711 commented
要不要加入一个Home按钮，因为网络驱动器将不会显示ThisPC，所以就无法返回主页。另外卡BladeView.IsLoaded的问题我没遇到诶

2021-05-07 07:48 UTC, silentmoooon commented
从thisPC点到一个盘之后,不能后退只能返回上一级.
可以加个.或者像explorer一样,在左边的驱动器上面加再一级thispc

2021-05-07 08:32 UTC, zhuxb711 commented
你再看看？应该问题都修好了

2021-05-07 12:42 UTC, merged